# Generated by Django 5.0.1 on 2024-10-22 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='Album',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='hotel_Main_Img',
            new_name='album_Img',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='name',
            new_name='image_name',
        ),
    ]
